/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "libsecret"

#define G_LOG_DOMAIN "libsecret"

#define HAVE_MLOCK

#define LIBGCRYPT_VERSION "1.2.2"

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_NAME "libsecret"

#define PACKAGE_STRING "libsecret"

#define PACKAGE_VERSION "0.21.0"

#undef WITH_DEBUG

#define WITH_GCRYPT

#undef WITH_TPM

#undef _DEBUG

