/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GETTEXT_PACKAGE "gdk-pixbuf-xlib"

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_TIME_H 1

#define HAVE_UNISTD_H 1

#define OS_LINUX 1

#define _GDK_PIXBUF_EXTERN __attribute__((visibility("default"))) extern

