/* automatically generated from xfce4-notifyd-config/xfce4-notifyd-config.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfce4_notifyd_config_ui)
#endif
#ifdef __GNUC__
static const char xfce4_notifyd_config_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfce4_notifyd_config_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".22.1 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.14\"/>\n  "
  "<requires lib=\"libxfce4ui-2\" version=\"4.12\"/>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\">\n    <property name=\"lower\">1</prop"
  "erty>\n    <property name=\"upper\">480</property>\n    <property name="
  "\"value\">10</property>\n    <property name=\"step_increment\">1</prope"
  "rty>\n    <property name=\"page_increment\">10</property>\n  </object>\n"
  "  <object class=\"GtkAdjustment\" id=\"adjustment2\">\n    <property na"
  "me=\"upper\">1.01</property>\n    <property name=\"value\">0.9000000000"
  "0000002</property>\n    <property name=\"step_increment\">0.01</propert"
  "y>\n    <property name=\"page_increment\">0.10000000000000001</property"
  ">\n    <property name=\"page_size\">0.01</property>\n  </object>\n  <ob"
  "ject class=\"GtkAdjustment\" id=\"adjustment3\">\n    <property name=\""
  "upper\">1000</property>\n    <property name=\"value\">100</property>\n "
  "   <property name=\"step_increment\">1</property>\n    <property name=\""
  "page_increment\">10</property>\n  </object>\n  <object class=\"GtkImage"
  "\" id=\"image2\">\n    <property name=\"visible\">True</property>\n    "
  "<property name=\"can_focus\">False</property>\n    <property name=\"ico"
  "n_name\">window-close-symbolic</property>\n  </object>\n  <object class"
  "=\"GtkImage\" id=\"image3\">\n    <property name=\"visible\">True</prop"
  "erty>\n    <property name=\"can_focus\">False</property>\n    <property"
  " name=\"icon_name\">help-browser</property>\n  </object>\n  <object cla"
  "ss=\"GtkListStore\" id=\"liststore1\">\n    <columns>\n      <!-- colum"
  "n-name gchararray -->\n      <column type=\"gchararray\"/>\n    </colum"
  "ns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">only during \"Do not disturb\"</col>\n      </row>\n      <row>\n     "
  "   <col id=\"0\" translatable=\"yes\">always</col>\n      </row>\n    <"
  "/data>\n  </object>\n  <object class=\"GtkListStore\" id=\"liststore2\""
  ">\n    <columns>\n      <!-- column-name gchararray -->\n      <column "
  "type=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n       "
  " <col id=\"0\" translatable=\"yes\">all</col>\n      </row>\n      <row"
  ">\n        <col id=\"0\" translatable=\"yes\">all except blocked</col>\n"
  "      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">o"
  "nly blocked</col>\n      </row>\n    </data>\n  </object>\n  <object cl"
  "ass=\"GtkListStore\" id=\"liststore3\">\n    <columns>\n      <!-- colu"
  "mn-name gchararray -->\n      <column type=\"gchararray\"/>\n    </colu"
  "mns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\"yes"
  "\">display with mouse pointer</col>\n      </row>\n      <row>\n       "
  " <col id=\"0\" translatable=\"yes\">primary display</col>\n      </row>"
  "\n    </data>\n  </object>\n  <object class=\"GtkListStore\" id=\"model"
  "1\">\n    <columns>\n      <!-- column-name gchararray -->\n      <colu"
  "mn type=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n    "
  "    <col id=\"0\" translatable=\"yes\">Top left</col>\n      </row>\n  "
  "    <row>\n        <col id=\"0\" translatable=\"yes\">Bottom left</col>"
  "\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Top right</col>\n      </row>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Bottom right</col>\n      </row>\n    </data>\n  </obj"
  "ect>\n  <object class=\"XfceTitledDialog\" id=\"notifyd_settings_dlg\">"
  "\n    <property name=\"can_focus\">False</property>\n    <property name"
  "=\"title\" translatable=\"yes\">Notifications</property>\n    <property"
  " name=\"window_position\">center-on-parent</property>\n    <property na"
  "me=\"default_width\">550</property>\n    <property name=\"default_heigh"
  "t\">600</property>\n    <property name=\"icon_name\">org.xfce.notificat"
  "ion</property>\n    <property name=\"type_hint\">dialog</property>\n   "
  " <property name=\"subtitle\" translatable=\"yes\">Customize your notifi"
  "cation settings</property>\n    <child internal-child=\"vbox\">\n      "
  "<object class=\"GtkBox\" id=\"dialog-vbox1\">\n        <property name=\""
  "visible\">True</property>\n        <property name=\"can_focus\">False</"
  "property>\n        <property name=\"orientation\">vertical</property>\n"
  "        <property name=\"spacing\">2</property>\n        <child interna"
  "l-child=\"action_area\">\n          <object class=\"GtkButtonBox\" id=\""
  "dialog-action_area1\">\n            <property name=\"visible\">True</pr"
  "operty>\n            <property name=\"can_focus\">False</property>\n   "
  "         <property name=\"hexpand\">True</property>\n            <prope"
  "rty name=\"homogeneous\">True</property>\n            <child>\n        "
  "      <object class=\"GtkButton\" id=\"help_btn\">\n                <pr"
  "operty name=\"label\" translatable=\"yes\">_Help</property>\n          "
  "      <property name=\"visible\">True</property>\n                <prop"
  "erty name=\"can_focus\">True</property>\n                <property name"
  "=\"receives_default\">True</property>\n                <property name=\""
  "image\">image3</property>\n                <property name=\"use_underli"
  "ne\">True</property>\n              </object>\n              <packing>\n"
  "                <property name=\"expand\">False</property>\n           "
  "     <property name=\"fill\">False</property>\n                <propert"
  "y name=\"position\">0</property>\n                <property name=\"seco"
  "ndary\">True</property>\n              </packing>\n            </child>"
  "\n            <child>\n              <object class=\"GtkButton\" id=\"c"
  "lose_btn\">\n                <property name=\"label\" translatable=\"ye"
  "s\">_Close</property>\n                <property name=\"use_action_appe"
  "arance\">False</property>\n                <property name=\"visible\">T"
  "rue</property>\n                <property name=\"can_focus\">True</prop"
  "erty>\n                <property name=\"receives_default\">True</proper"
  "ty>\n                <property name=\"image\">image2</property>\n      "
  "          <property name=\"use_underline\">True</property>\n           "
  "   </object>\n              <packing>\n                <property name=\""
  "expand\">True</property>\n                <property name=\"fill\">True<"
  "/property>\n                <property name=\"pack_type\">end</property>"
  "\n                <property name=\"position\">1</property>\n           "
  "   </packing>\n            </child>\n          </object>\n          <pa"
  "cking>\n            <property name=\"expand\">True</property>\n        "
  "    <property name=\"fill\">True</property>\n            <property name"
  "=\"position\">0</property>\n          </packing>\n        </child>\n   "
  "     <child>\n          <object class=\"GtkBox\" id=\"plug-child\">\n  "
  "          <property name=\"visible\">True</property>\n            <prop"
  "erty name=\"can_focus\">False</property>\n            <property name=\""
  "border_width\">6</property>\n            <property name=\"orientation\""
  ">vertical</property>\n            <child>\n              <object class="
  "\"GtkRevealer\" id=\"notifyd_running\">\n                <property name"
  "=\"visible\">True</property>\n                <property name=\"can_focu"
  "s\">False</property>\n                <property name=\"margin_bottom\">"
  "12</property>\n                <property name=\"reveal_child\">True</pr"
  "operty>\n                <child>\n                  <object class=\"Gtk"
  "InfoBar\" id=\"infobar2\">\n                    <property name=\"visibl"
  "e\">True</property>\n                    <property name=\"can_focus\">F"
  "alse</property>\n                    <property name=\"message_type\">wa"
  "rning</property>\n                    <child internal-child=\"action_ar"
  "ea\">\n                      <object class=\"GtkButtonBox\">\n         "
  "               <property name=\"can_focus\">False</property>\n         "
  "               <property name=\"spacing\">6</property>\n               "
  "         <property name=\"layout_style\">end</property>\n              "
  "          <child>\n                          <placeholder/>\n          "
  "              </child>\n                        <child>\n              "
  "            <placeholder/>\n                        </child>\n         "
  "             </object>\n                      <packing>\n              "
  "          <property name=\"expand\">False</property>\n                 "
  "       <property name=\"fill\">False</property>\n                      "
  "  <property name=\"position\">0</property>\n                      </pac"
  "king>\n                    </child>\n                    <child interna"
  "l-child=\"content_area\">\n                      <object class=\"GtkBox"
  "\">\n                        <property name=\"can_focus\">False</proper"
  "ty>\n                        <property name=\"spacing\">16</property>\n"
  "                        <child>\n                          <object clas"
  "s=\"GtkLabel\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"can_focu"
  "s\">False</property>\n                            <property name=\"labe"
  "l\" translatable=\"yes\">The notification service is not running. No no"
  "tifications will be shown.</property>\n                          </obje"
  "ct>\n                          <packing>\n                            <"
  "property name=\"expand\">True</property>\n                            <"
  "property name=\"fill\">True</property>\n                            <pr"
  "operty name=\"position\">0</property>\n                          </pack"
  "ing>\n                        </child>\n                        <child>"
  "\n                          <placeholder/>\n                        </c"
  "hild>\n                        <child>\n                          <plac"
  "eholder/>\n                        </child>\n                      </ob"
  "ject>\n                      <packing>\n                        <proper"
  "ty name=\"expand\">False</property>\n                        <property "
  "name=\"fill\">False</property>\n                        <property name="
  "\"position\">0</property>\n                      </packing>\n          "
  "          </child>\n                    <child>\n                      "
  "<placeholder/>\n                    </child>\n                  </objec"
  "t>\n                </child>\n              </object>\n              <p"
  "acking>\n                <property name=\"expand\">False</property>\n  "
  "              <property name=\"fill\">True</property>\n                "
  "<property name=\"position\">0</property>\n              </packing>\n   "
  "         </child>\n            <child>\n              <object class=\"G"
  "tkRevealer\" id=\"do_not_disturb_info\">\n                <property nam"
  "e=\"visible\">True</property>\n                <property name=\"can_foc"
  "us\">False</property>\n                <property name=\"margin_bottom\""
  ">12</property>\n                <property name=\"reveal_child\">True</p"
  "roperty>\n                <child>\n                  <object class=\"Gt"
  "kInfoBar\" id=\"infobar1\">\n                    <property name=\"visib"
  "le\">True</property>\n                    <property name=\"app_paintabl"
  "e\">True</property>\n                    <property name=\"can_focus\">F"
  "alse</property>\n                    <child internal-child=\"action_are"
  "a\">\n                      <object class=\"GtkButtonBox\" id=\"infobar"
  "-action_area\">\n                        <property name=\"can_focus\">F"
  "alse</property>\n                        <property name=\"spacing\">6</"
  "property>\n                        <property name=\"layout_style\">star"
  "t</property>\n                        <child>\n                        "
  "  <placeholder/>\n                        </child>\n                   "
  "   </object>\n                      <packing>\n                        "
  "<property name=\"expand\">True</property>\n                        <pro"
  "perty name=\"fill\">True</property>\n                        <property "
  "name=\"position\">0</property>\n                      </packing>\n     "
  "               </child>\n                    <child internal-child=\"co"
  "ntent_area\">\n                      <object class=\"GtkBox\" id=\"info"
  "bar-content_area\">\n                        <property name=\"name\">8<"
  "/property>\n                        <property name=\"can_focus\">False<"
  "/property>\n                        <child>\n                          "
  "<object class=\"GtkBox\" id=\"box1\">\n                            <pro"
  "perty name=\"visible\">True</property>\n                            <pr"
  "operty name=\"can_focus\">False</property>\n                           "
  " <property name=\"spacing\">18</property>\n                            "
  "<child>\n                              <object class=\"GtkImage\" id=\""
  "image1\">\n                                <property name=\"visible\">T"
  "rue</property>\n                                <property name=\"can_fo"
  "cus\">False</property>\n                                <property name="
  "\"icon_name\">dialog-information-symbolic</property>\n                 "
  "               <property name=\"icon_size\">1</property>\n             "
  "                 </object>\n                              <packing>\n  "
  "                              <property name=\"expand\">False</property"
  ">\n                                <property name=\"fill\">True</proper"
  "ty>\n                                <property name=\"position\">0</pro"
  "perty>\n                              </packing>\n                     "
  "       </child>\n                            <child>\n                 "
  "             <object class=\"GtkLabel\" id=\"infobar_label\">\n        "
  "                        <property name=\"visible\">True</property>\n   "
  "                             <property name=\"can_focus\">False</proper"
  "ty>\n                                <property name=\"label\" translata"
  "ble=\"yes\">&lt;b&gt;Currently only urgent notifications are shown.&lt;"
  "/b&gt;</property>\n                                <property name=\"use"
  "_markup\">True</property>\n                                <property na"
  "me=\"ellipsize\">end</property>\n                                <prope"
  "rty name=\"xalign\">0</property>\n                              </objec"
  "t>\n                              <packing>\n                          "
  "      <property name=\"expand\">True</property>\n                      "
  "          <property name=\"fill\">True</property>\n                    "
  "            <property name=\"position\">1</property>\n                 "
  "             </packing>\n                            </child>\n        "
  "                  </object>\n                          <packing>\n     "
  "                       <property name=\"expand\">False</property>\n    "
  "                        <property name=\"fill\">True</property>\n      "
  "                      <property name=\"position\">0</property>\n       "
  "                   </packing>\n                        </child>\n      "
  "                </object>\n                      <packing>\n           "
  "             <property name=\"expand\">False</property>\n              "
  "          <property name=\"fill\">True</property>\n                    "
  "    <property name=\"position\">0</property>\n                      </p"
  "acking>\n                    </child>\n                    <child>\n   "
  "                   <placeholder/>\n                    </child>\n      "
  "            </object>\n                </child>\n              </object"
  ">\n              <packing>\n                <property name=\"expand\">F"
  "alse</property>\n                <property name=\"fill\">True</property"
  ">\n                <property name=\"position\">1</property>\n          "
  "    </packing>\n            </child>\n            <child>\n            "
  "  <object class=\"GtkStackSwitcher\" id=\"stack_switcher\">\n          "
  "      <property name=\"visible\">True</property>\n                <prop"
  "erty name=\"can_focus\">False</property>\n                <property nam"
  "e=\"halign\">center</property>\n                <property name=\"margin"
  "_left\">12</property>\n                <property name=\"margin_right\">"
  "12</property>\n                <property name=\"stack\">stack</property"
  ">\n              </object>\n              <packing>\n                <p"
  "roperty name=\"expand\">False</property>\n                <property nam"
  "e=\"fill\">False</property>\n                <property name=\"position\""
  ">2</property>\n              </packing>\n            </child>\n        "
  "    <child>\n              <object class=\"GtkStack\" id=\"stack\">\n  "
  "              <property name=\"visible\">True</property>\n             "
  "   <property name=\"can_focus\">False</property>\n                <prop"
  "erty name=\"transition_type\">slide-left-right</property>\n            "
  "    <child>\n                  <object class=\"GtkGrid\" id=\"appearanc"
  "e\">\n                    <property name=\"visible\">True</property>\n "
  "                   <property name=\"can_focus\">False</property>\n     "
  "               <property name=\"margin_left\">12</property>\n          "
  "          <property name=\"margin_right\">12</property>\n              "
  "      <property name=\"margin_top\">12</property>\n                    "
  "<property name=\"margin_bottom\">12</property>\n                    <pr"
  "operty name=\"row_spacing\">6</property>\n                    <property"
  " name=\"column_spacing\">12</property>\n                    <property n"
  "ame=\"column_homogeneous\">True</property>\n                    <child>"
  "\n                      <object class=\"GtkScale\" id=\"opacity_slider\""
  ">\n                        <property name=\"visible\">True</property>\n"
  "                        <property name=\"can_focus\">True</property>\n "
  "                       <property name=\"adjustment\">adjustment2</prope"
  "rty>\n                        <property name=\"round_digits\">2</proper"
  "ty>\n                        <property name=\"digits\">2</property>\n  "
  "                      <property name=\"value_pos\">right</property>\n  "
  "                    </object>\n                      <packing>\n       "
  "                 <property name=\"left_attach\">1</property>\n         "
  "               <property name=\"top_attach\">6</property>\n            "
  "          </packing>\n                    </child>\n                   "
  " <child>\n                      <object class=\"GtkButton\" id=\"previe"
  "w_button\">\n                        <property name=\"label\" translata"
  "ble=\"yes\">Show _Preview</property>\n                        <property"
  " name=\"visible\">True</property>\n                        <property na"
  "me=\"can_focus\">True</property>\n                        <property nam"
  "e=\"receives_default\">True</property>\n                        <proper"
  "ty name=\"margin_top\">6</property>\n                        <property "
  "name=\"use_underline\">True</property>\n                      </object>"
  "\n                      <packing>\n                        <property na"
  "me=\"left_attach\">1</property>\n                        <property name"
  "=\"top_attach\">11</property>\n                      </packing>\n      "
  "              </child>\n                    <child>\n                  "
  "    <object class=\"GtkBox\" id=\"hbox4\">\n                        <pr"
  "operty name=\"visible\">True</property>\n                        <prope"
  "rty name=\"can_focus\">False</property>\n                        <prope"
  "rty name=\"spacing\">6</property>\n                        <child>\n   "
  "                       <object class=\"GtkLabel\" id=\"label4\">\n     "
  "                       <property name=\"visible\">True</property>\n    "
  "                        <property name=\"can_focus\">False</property>\n"
  "                            <property name=\"label\" translatable=\"yes"
  "\">seconds</property>\n                            <property name=\"xal"
  "ign\">0</property>\n                          </object>\n              "
  "            <packing>\n                            <property name=\"exp"
  "and\">False</property>\n                            <property name=\"fi"
  "ll\">True</property>\n                            <property name=\"pack"
  "_type\">end</property>\n                            <property name=\"po"
  "sition\">0</property>\n                          </packing>\n          "
  "              </child>\n                        <child>\n              "
  "            <object class=\"GtkSpinButton\" id=\"expire_timeout_sbtn\">"
  "\n                            <property name=\"visible\">True</property"
  ">\n                            <property name=\"can_focus\">True</prope"
  "rty>\n                            <property name=\"invisible_char\">\342"
  "\227\217</property>\n                            <property name=\"prima"
  "ry_icon_activatable\">False</property>\n                            <pr"
  "operty name=\"secondary_icon_activatable\">False</property>\n          "
  "                  <property name=\"adjustment\">adjustment1</property>\n"
  "                            <property name=\"numeric\">True</property>\n"
  "                          </object>\n                          <packing"
  ">\n                            <property name=\"expand\">False</propert"
  "y>\n                            <property name=\"fill\">False</property"
  ">\n                            <property name=\"pack_type\">end</proper"
  "ty>\n                            <property name=\"position\">1</propert"
  "y>\n                          </packing>\n                        </chi"
  "ld>\n                      </object>\n                      <packing>\n"
  "                        <property name=\"left_attach\">1</property>\n  "
  "                      <property name=\"top_attach\">7</property>\n     "
  "                 </packing>\n                    </child>\n            "
  "        <child>\n                      <object class=\"GtkLabel\" id=\""
  "label1\">\n                        <property name=\"visible\">True</pro"
  "perty>\n                        <property name=\"can_focus\">False</pro"
  "perty>\n                        <property name=\"margin_left\">12</prop"
  "erty>\n                        <property name=\"label\" translatable=\""
  "yes\">_Disappear after</property>\n                        <property na"
  "me=\"use_underline\">True</property>\n                        <property"
  " name=\"mnemonic_widget\">expire_timeout_sbtn</property>\n             "
  "           <property name=\"xalign\">0</property>\n                    "
  "  </object>\n                      <packing>\n                        <"
  "property name=\"left_attach\">0</property>\n                        <pr"
  "operty name=\"top_attach\">7</property>\n                      </packin"
  "g>\n                    </child>\n                    <child>\n        "
  "              <object class=\"GtkLabel\" id=\"label2\">\n              "
  "          <property name=\"visible\">True</property>\n                 "
  "       <property name=\"can_focus\">False</property>\n                 "
  "       <property name=\"margin_left\">12</property>\n                  "
  "      <property name=\"label\" translatable=\"yes\">_Opacity</property>"
  "\n                        <property name=\"use_underline\">True</proper"
  "ty>\n                        <property name=\"xalign\">0</property>\n  "
  "                    </object>\n                      <packing>\n       "
  "                 <property name=\"left_attach\">0</property>\n         "
  "               <property name=\"top_attach\">6</property>\n            "
  "          </packing>\n                    </child>\n                   "
  " <child>\n                      <object class=\"GtkSwitch\" id=\"do_fad"
  "eout\">\n                        <property name=\"visible\">True</prope"
  "rty>\n                        <property name=\"can_focus\">True</proper"
  "ty>\n                        <property name=\"halign\">end</property>\n"
  "                        <property name=\"valign\">center</property>\n  "
  "                    </object>\n                      <packing>\n       "
  "                 <property name=\"left_attach\">1</property>\n         "
  "               <property name=\"top_attach\">9</property>\n            "
  "          </packing>\n                    </child>\n                   "
  " <child>\n                      <object class=\"GtkLabel\" id=\"label13"
  "\">\n                        <property name=\"visible\">True</property>"
  "\n                        <property name=\"can_focus\">False</property>"
  "\n                        <property name=\"margin_left\">12</property>\n"
  "                        <property name=\"label\" translatable=\"yes\">F"
  "ade out</property>\n                        <property name=\"xalign\">0"
  "</property>\n                      </object>\n                      <pa"
  "cking>\n                        <property name=\"left_attach\">0</prope"
  "rty>\n                        <property name=\"top_attach\">9</property"
  ">\n                      </packing>\n                    </child>\n    "
  "                <child>\n                      <object class=\"GtkLabel"
  "\" id=\"do_slideout_label\">\n                        <property name=\""
  "visible\">True</property>\n                        <property name=\"can"
  "_focus\">False</property>\n                        <property name=\"mar"
  "gin_left\">12</property>\n                        <property name=\"labe"
  "l\" translatable=\"yes\">_Slide out</property>\n                       "
  " <property name=\"use_underline\">True</property>\n                    "
  "    <property name=\"xalign\">0</property>\n                      </obj"
  "ect>\n                      <packing>\n                        <propert"
  "y name=\"left_attach\">0</property>\n                        <property "
  "name=\"top_attach\">10</property>\n                      </packing>\n  "
  "                  </child>\n                    <child>\n              "
  "        <object class=\"GtkSwitch\" id=\"do_slideout\">\n              "
  "          <property name=\"visible\">True</property>\n                 "
  "       <property name=\"can_focus\">True</property>\n                  "
  "      <property name=\"halign\">end</property>\n                       "
  " <property name=\"valign\">center</property>\n                      </o"
  "bject>\n                      <packing>\n                        <prope"
  "rty name=\"left_attach\">1</property>\n                        <propert"
  "y name=\"top_attach\">10</property>\n                      </packing>\n"
  "                    </child>\n                    <child>\n            "
  "          <object class=\"GtkLabel\" id=\"label3\">\n                  "
  "      <property name=\"visible\">True</property>\n                     "
  "   <property name=\"can_focus\">False</property>\n                     "
  "   <property name=\"margin_left\">12</property>\n                      "
  "  <property name=\"label\" translatable=\"yes\">Default _position</prop"
  "erty>\n                        <property name=\"use_underline\">True</p"
  "roperty>\n                        <property name=\"xalign\">0</property"
  ">\n                      </object>\n                      <packing>\n  "
  "                      <property name=\"left_attach\">0</property>\n    "
  "                    <property name=\"top_attach\">5</property>\n       "
  "               </packing>\n                    </child>\n              "
  "      <child>\n                      <object class=\"GtkComboBox\" id=\""
  "position_combo\">\n                        <property name=\"visible\">T"
  "rue</property>\n                        <property name=\"can_focus\">Fa"
  "lse</property>\n                        <property name=\"model\">model1"
  "</property>\n                        <child>\n                         "
  " <object class=\"GtkCellRendererText\" id=\"renderer3\"/>\n            "
  "              <attributes>\n                            <attribute name"
  "=\"text\">0</attribute>\n                          </attributes>\n     "
  "                   </child>\n                      </object>\n         "
  "             <packing>\n                        <property name=\"left_a"
  "ttach\">1</property>\n                        <property name=\"top_atta"
  "ch\">5</property>\n                      </packing>\n                  "
  "  </child>\n                    <child>\n                      <object "
  "class=\"GtkComboBox\" id=\"theme_combo\">\n                        <pro"
  "perty name=\"name\">theme</property>\n                        <property"
  " name=\"visible\">True</property>\n                        <property na"
  "me=\"can_focus\">False</property>\n                        <child>\n   "
  "                       <object class=\"GtkCellRendererText\" id=\"rende"
  "rer1\"/>\n                          <attributes>\n                     "
  "       <attribute name=\"text\">0</attribute>\n                        "
  "  </attributes>\n                        </child>\n                    "
  "  </object>\n                      <packing>\n                        <"
  "property name=\"left_attach\">1</property>\n                        <pr"
  "operty name=\"top_attach\">4</property>\n                      </packin"
  "g>\n                    </child>\n                    <child>\n        "
  "              <object class=\"GtkLabel\" id=\"label5\">\n              "
  "          <property name=\"visible\">True</property>\n                 "
  "       <property name=\"can_focus\">False</property>\n                 "
  "       <property name=\"margin_left\">12</property>\n                  "
  "      <property name=\"label\" translatable=\"yes\">_Theme</property>\n"
  "                        <property name=\"use_underline\">True</property"
  ">\n                        <property name=\"xalign\">0</property>\n    "
  "                  </object>\n                      <packing>\n         "
  "               <property name=\"left_attach\">0</property>\n           "
  "             <property name=\"top_attach\">4</property>\n              "
  "        </packing>\n                    </child>\n                    <"
  "child>\n                      <object class=\"GtkLabel\" id=\"do_not_di"
  "sturb_label\">\n                        <property name=\"visible\">True"
  "</property>\n                        <property name=\"can_focus\">False"
  "</property>\n                        <property name=\"margin_left\">12<"
  "/property>\n                        <property name=\"hexpand\">True</pr"
  "operty>\n                        <property name=\"label\" translatable="
  "\"yes\">Do not disturb</property>\n                        <property na"
  "me=\"xalign\">0</property>\n                      </object>\n          "
  "            <packing>\n                        <property name=\"left_at"
  "tach\">0</property>\n                        <property name=\"top_attac"
  "h\">1</property>\n                      </packing>\n                   "
  " </child>\n                    <child>\n                      <object c"
  "lass=\"GtkSwitch\" id=\"do_not_disturb\">\n                        <pro"
  "perty name=\"visible\">True</property>\n                        <proper"
  "ty name=\"can_focus\">True</property>\n                        <propert"
  "y name=\"halign\">end</property>\n                        <property nam"
  "e=\"valign\">center</property>\n                      </object>\n      "
  "                <packing>\n                        <property name=\"lef"
  "t_attach\">1</property>\n                        <property name=\"top_a"
  "ttach\">1</property>\n                      </packing>\n               "
  "     </child>\n                    <child>\n                      <obje"
  "ct class=\"GtkLabel\">\n                        <property name=\"visibl"
  "e\">True</property>\n                        <property name=\"can_focus"
  "\">False</property>\n                        <property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Behavior&lt;/b&gt;</property>\n           "
  "             <property name=\"use_markup\">True</property>\n           "
  "             <property name=\"xalign\">0</property>\n                  "
  "    </object>\n                      <packing>\n                       "
  " <property name=\"left_attach\">0</property>\n                        <"
  "property name=\"top_attach\">0</property>\n                      </pack"
  "ing>\n                    </child>\n                    <child>\n      "
  "                <object class=\"GtkLabel\">\n                        <p"
  "roperty name=\"visible\">True</property>\n                        <prop"
  "erty name=\"can_focus\">False</property>\n                        <prop"
  "erty name=\"margin_top\">12</property>\n                        <proper"
  "ty name=\"label\" translatable=\"yes\">&lt;b&gt;Appearance&lt;/b&gt;</p"
  "roperty>\n                        <property name=\"use_markup\">True</p"
  "roperty>\n                        <property name=\"xalign\">0</property"
  ">\n                      </object>\n                      <packing>\n  "
  "                      <property name=\"left_attach\">0</property>\n    "
  "                    <property name=\"top_attach\">3</property>\n       "
  "               </packing>\n                    </child>\n              "
  "      <child>\n                      <object class=\"GtkLabel\">\n     "
  "                   <property name=\"visible\">True</property>\n        "
  "                <property name=\"can_focus\">False</property>\n        "
  "                <property name=\"margin_top\">12</property>\n          "
  "              <property name=\"label\" translatable=\"yes\">&lt;b&gt;An"
  "imations&lt;/b&gt;</property>\n                        <property name=\""
  "use_markup\">True</property>\n                        <property name=\""
  "xalign\">0</property>\n                      </object>\n               "
  "       <packing>\n                        <property name=\"left_attach\""
  ">0</property>\n                        <property name=\"top_attach\">8<"
  "/property>\n                      </packing>\n                    </chi"
  "ld>\n                    <child>\n                      <object class=\""
  "GtkComboBox\" id=\"primary_monitor\">\n                        <propert"
  "y name=\"visible\">True</property>\n                        <property n"
  "ame=\"can_focus\">False</property>\n                        <property n"
  "ame=\"model\">liststore3</property>\n                        <property "
  "name=\"active_id\">1</property>\n                        <child>\n     "
  "                     <object class=\"GtkCellRendererText\" id=\"rendere"
  "r5\"/>\n                          <attributes>\n                       "
  "     <attribute name=\"text\">0</attribute>\n                          "
  "</attributes>\n                        </child>\n                      "
  "</object>\n                      <packing>\n                        <pr"
  "operty name=\"left_attach\">1</property>\n                        <prop"
  "erty name=\"top_attach\">2</property>\n                      </packing>"
  "\n                    </child>\n                    <child>\n          "
  "            <object class=\"GtkLabel\" id=\"primary_label\">\n         "
  "               <property name=\"visible\">True</property>\n            "
  "            <property name=\"can_focus\">False</property>\n            "
  "            <property name=\"tooltip_text\" translatable=\"yes\">By def"
  "ault the notification bubbles will be shown on the display on which the"
  " mouse pointer is located.</property>\n                        <propert"
  "y name=\"margin_left\">12</property>\n                        <property"
  " name=\"label\" translatable=\"yes\">Show notifications on</property>\n"
  "                        <property name=\"ellipsize\">end</property>\n  "
  "                      <property name=\"xalign\">0</property>\n         "
  "             </object>\n                      <packing>\n              "
  "          <property name=\"left_attach\">0</property>\n                "
  "        <property name=\"top_attach\">2</property>\n                   "
  "   </packing>\n                    </child>\n                    <child"
  ">\n                      <placeholder/>\n                    </child>\n"
  "                    <child>\n                      <placeholder/>\n    "
  "                </child>\n                    <child>\n                "
  "      <placeholder/>\n                    </child>\n                   "
  " <child>\n                      <placeholder/>\n                    </c"
  "hild>\n                  </object>\n                  <packing>\n      "
  "              <property name=\"name\">general</property>\n             "
  "       <property name=\"title\" translatable=\"yes\">General</property>"
  "\n                  </packing>\n                </child>\n             "
  "   <child>\n                  <object class=\"GtkGrid\" id=\"applicatio"
  "ns\">\n                    <property name=\"visible\">True</property>\n"
  "                    <property name=\"can_focus\">False</property>\n    "
  "                <property name=\"margin_left\">12</property>\n         "
  "           <property name=\"margin_right\">12</property>\n             "
  "       <property name=\"margin_top\">12</property>\n                   "
  " <property name=\"margin_bottom\">12</property>\n                    <c"
  "hild>\n                      <object class=\"GtkLabel\" id=\"label9\">\n"
  "                        <property name=\"visible\">True</property>\n   "
  "                     <property name=\"can_focus\">False</property>\n   "
  "                     <property name=\"margin_bottom\">6</property>\n   "
  "                     <property name=\"label\" translatable=\"yes\">&lt;"
  "b&gt;Show or block notifications per application&lt;/b&gt;</property>\n"
  "                        <property name=\"use_markup\">True</property>\n"
  "                        <property name=\"xalign\">0</property>\n       "
  "               </object>\n                      <packing>\n            "
  "            <property name=\"left_attach\">0</property>\n              "
  "          <property name=\"top_attach\">0</property>\n                 "
  "       <property name=\"width\">2</property>\n                      </p"
  "acking>\n                    </child>\n                    <child>\n   "
  "                   <object class=\"GtkScrolledWindow\" id=\"known_appli"
  "cations_scrolled_window\">\n                        <property name=\"vi"
  "sible\">True</property>\n                        <property name=\"can_f"
  "ocus\">True</property>\n                        <property name=\"hexpan"
  "d\">True</property>\n                        <property name=\"vexpand\""
  ">True</property>\n                        <property name=\"shadow_type\""
  ">in</property>\n                      </object>\n                      "
  "<packing>\n                        <property name=\"left_attach\">0</pr"
  "operty>\n                        <property name=\"top_attach\">1</prope"
  "rty>\n                        <property name=\"width\">2</property>\n  "
  "                    </packing>\n                    </child>\n         "
  "         </object>\n                  <packing>\n                    <p"
  "roperty name=\"name\">applications</property>\n                    <pro"
  "perty name=\"title\" translatable=\"yes\">Applications</property>\n    "
  "                <property name=\"position\">1</property>\n             "
  "     </packing>\n                </child>\n                <child>\n   "
  "               <object class=\"GtkGrid\" id=\"log\">\n                 "
  "   <property name=\"visible\">True</property>\n                    <pro"
  "perty name=\"can_focus\">False</property>\n                    <propert"
  "y name=\"margin_left\">12</property>\n                    <property nam"
  "e=\"margin_right\">12</property>\n                    <property name=\""
  "margin_top\">12</property>\n                    <property name=\"margin"
  "_bottom\">12</property>\n                    <property name=\"row_spaci"
  "ng\">6</property>\n                    <property name=\"column_spacing\""
  ">12</property>\n                    <child>\n                      <obj"
  "ect class=\"GtkLabel\" id=\"log_level_label\">\n                       "
  " <property name=\"visible\">True</property>\n                        <p"
  "roperty name=\"can_focus\">False</property>\n                        <p"
  "roperty name=\"label\" translatable=\"yes\">Log notifications</property"
  ">\n                        <property name=\"xalign\">0</property>\n    "
  "                  </object>\n                      <packing>\n         "
  "               <property name=\"left_attach\">0</property>\n           "
  "             <property name=\"top_attach\">0</property>\n              "
  "        </packing>\n                    </child>\n                    <"
  "child>\n                      <object class=\"GtkSwitch\" id=\"log_swit"
  "ch\">\n                        <property name=\"visible\">True</propert"
  "y>\n                        <property name=\"can_focus\">True</property"
  ">\n                        <property name=\"halign\">end</property>\n  "
  "                      <property name=\"valign\">center</property>\n    "
  "                  </object>\n                      <packing>\n         "
  "               <property name=\"left_attach\">2</property>\n           "
  "             <property name=\"top_attach\">0</property>\n              "
  "        </packing>\n                    </child>\n                    <"
  "child>\n                      <object class=\"GtkComboBox\" id=\"log_le"
  "vel\">\n                        <property name=\"visible\">True</proper"
  "ty>\n                        <property name=\"can_focus\">False</proper"
  "ty>\n                        <property name=\"model\">liststore1</prope"
  "rty>\n                        <property name=\"active_id\">1</property>"
  "\n                        <child>\n                          <object cl"
  "ass=\"GtkCellRendererText\" id=\"renderer2\"/>\n                       "
  "   <attributes>\n                            <attribute name=\"text\">0"
  "</attribute>\n                          </attributes>\n                "
  "        </child>\n                      </object>\n                    "
  "  <packing>\n                        <property name=\"left_attach\">1</"
  "property>\n                        <property name=\"top_attach\">0</pro"
  "perty>\n                      </packing>\n                    </child>\n"
  "                    <child>\n                      <object class=\"GtkL"
  "abel\" id=\"log_level_apps_label\">\n                        <property "
  "name=\"visible\">True</property>\n                        <property nam"
  "e=\"can_focus\">False</property>\n                        <property nam"
  "e=\"label\" translatable=\"yes\">Log applications</property>\n         "
  "               <property name=\"xalign\">0</property>\n                "
  "      </object>\n                      <packing>\n                     "
  "   <property name=\"left_attach\">0</property>\n                       "
  " <property name=\"top_attach\">1</property>\n                      </pa"
  "cking>\n                    </child>\n                    <child>\n    "
  "                  <object class=\"GtkBox\">\n                        <p"
  "roperty name=\"visible\">True</property>\n                        <prop"
  "erty name=\"can_focus\">False</property>\n                        <prop"
  "erty name=\"hexpand\">True</property>\n                        <propert"
  "y name=\"vexpand\">True</property>\n                        <property n"
  "ame=\"orientation\">vertical</property>\n                        <child"
  ">\n                          <object class=\"GtkScrolledWindow\" id=\"l"
  "og_scrolled_window\">\n                            <property name=\"vis"
  "ible\">True</property>\n                            <property name=\"ca"
  "n_focus\">True</property>\n                            <property name=\""
  "hexpand\">True</property>\n                            <property name=\""
  "vexpand\">True</property>\n                            <property name=\""
  "shadow_type\">in</property>\n                          </object>\n     "
  "                     <packing>\n                            <property n"
  "ame=\"expand\">False</property>\n                            <property "
  "name=\"fill\">True</property>\n                            <property na"
  "me=\"position\">0</property>\n                          </packing>\n   "
  "                     </child>\n                        <child>\n       "
  "                   <object class=\"GtkToolbar\" id=\"log_toolbar\">\n  "
  "                          <property name=\"visible\">True</property>\n "
  "                           <property name=\"can_focus\">False</property"
  ">\n                            <style>\n                              <"
  "class name=\"inline-toolbar\"/>\n                            </style>\n"
  "                          </object>\n                          <packing"
  ">\n                            <property name=\"expand\">False</propert"
  "y>\n                            <property name=\"fill\">True</property>"
  "\n                            <property name=\"position\">1</property>\n"
  "                          </packing>\n                        </child>\n"
  "                      </object>\n                      <packing>\n     "
  "                   <property name=\"left_attach\">0</property>\n       "
  "                 <property name=\"top_attach\">3</property>\n          "
  "              <property name=\"width\">3</property>\n                  "
  "    </packing>\n                    </child>\n                    <chil"
  "d>\n                      <object class=\"GtkComboBox\" id=\"log_level_"
  "apps\">\n                        <property name=\"visible\">True</prope"
  "rty>\n                        <property name=\"can_focus\">False</prope"
  "rty>\n                        <property name=\"hexpand\">True</property"
  ">\n                        <property name=\"model\">liststore2</propert"
  "y>\n                        <property name=\"active_id\">0</property>\n"
  "                        <child>\n                          <object clas"
  "s=\"GtkCellRendererText\" id=\"renderer4\"/>\n                         "
  " <attributes>\n                            <attribute name=\"text\">0</"
  "attribute>\n                          </attributes>\n                  "
  "      </child>\n                      </object>\n                      "
  "<packing>\n                        <property name=\"left_attach\">1</pr"
  "operty>\n                        <property name=\"top_attach\">1</prope"
  "rty>\n                      </packing>\n                    </child>\n "
  "                   <child>\n                      <object class=\"GtkLa"
  "bel\">\n                        <property name=\"visible\">True</proper"
  "ty>\n                        <property name=\"can_focus\">False</proper"
  "ty>\n                        <property name=\"label\" translatable=\"ye"
  "s\">Log size limit</property>\n                        <property name=\""
  "xalign\">0</property>\n                      </object>\n               "
  "       <packing>\n                        <property name=\"left_attach\""
  ">0</property>\n                        <property name=\"top_attach\">2<"
  "/property>\n                      </packing>\n                    </chi"
  "ld>\n                    <child>\n                      <object class=\""
  "GtkSpinButton\" id=\"log_max_size\">\n                        <property"
  " name=\"visible\">True</property>\n                        <property na"
  "me=\"can_focus\">True</property>\n                        <property nam"
  "e=\"tooltip_text\" translatable=\"yes\">The maximum amount of entries t"
  "o be retained in the log. Please note that a large log may lead to perf"
  "ormance penalties. 0 means no limit.</property>\n                      "
  "  <property name=\"halign\">end</property>\n                        <pr"
  "operty name=\"width_chars\">5</property>\n                        <prop"
  "erty name=\"adjustment\">adjustment3</property>\n                      "
  "</object>\n                      <packing>\n                        <pr"
  "operty name=\"left_attach\">1</property>\n                        <prop"
  "erty name=\"top_attach\">2</property>\n                      </packing>"
  "\n                    </child>\n                    <child>\n          "
  "            <placeholder/>\n                    </child>\n             "
  "       <child>\n                      <placeholder/>\n                 "
  "   </child>\n                  </object>\n                  <packing>\n"
  "                    <property name=\"name\">log</property>\n           "
  "         <property name=\"title\" translatable=\"yes\">Log</property>\n"
  "                    <property name=\"position\">2</property>\n         "
  "         </packing>\n                </child>\n              </object>\n"
  "              <packing>\n                <property name=\"expand\">True"
  "</property>\n                <property name=\"fill\">True</property>\n "
  "               <property name=\"position\">3</property>\n              "
  "</packing>\n            </child>\n          </object>\n          <packi"
  "ng>\n            <property name=\"expand\">True</property>\n           "
  " <property name=\"fill\">True</property>\n            <property name=\""
  "position\">1</property>\n          </packing>\n        </child>\n      "
  "</object>\n    </child>\n    <action-widgets>\n      <action-widget res"
  "ponse=\"1\">close_btn</action-widget>\n    </action-widgets>\n  </objec"
  "t>\n</interface>\n"
};

static const unsigned xfce4_notifyd_config_ui_length = 45494u;

